name: loke_task_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audio_waveforms: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova-extrabold.otf
          weight: 700
        - asset: assets/fonts/proximanova-semibold.otf
          weight: 600
        - asset: assets/fonts/proximanova-regular.otf
          weight: 400
        - asset: assets/fonts/proximanova-regularit.otf
          weight: 400
          style: italic
